#!/usr/bin/env python3
"""
Build geogames/data/countries.js by merging three sources:

  1. ../atlas/data/countries.js  - the 194 UN member states this site already
     knows, with hand-curated fame tiers, name aliases and flag filenames.
  2. mledoze/countries (ODbL)    - area, borders, coordinates, currency,
     languages, demonym, calling code, landlocked flag, ISO alpha-3.
  3. Natural Earth 1:50m         - population estimates (POP_EST).

Facts about countries are not copyrightable; the compilations above are
credited in geogames/NOTICE.md.

Usage:  python3 tools/build-countries.py ATLAS.js MLEDOZE.json NE.geojson OUT.js
"""
import json
import re
import sys


def load_atlas(path):
    """Pull the COUNTRIES array out of the existing ES module without executing it."""
    src = open(path, encoding="utf-8").read()
    rows = []
    for line in src.splitlines():
        line = line.strip().rstrip(",")
        if line.startswith('{"iso"'):
            rows.append(json.loads(line))
    return rows


def main():
    atlas_path, mledoze_path, ne_path, out_path = sys.argv[1:5]

    base = load_atlas(atlas_path)
    mledoze = {c["cca2"]: c for c in json.load(open(mledoze_path, encoding="utf-8"))}
    a3_to_a2 = {c["cca3"]: c["cca2"] for c in mledoze.values()}

    pop = {}
    for feat in json.load(open(ne_path, encoding="utf-8"))["features"]:
        props = feat["properties"]
        iso = props.get("ISO_A2_EH") or props.get("ISO_A2")
        if props.get("POP_EST"):
            pop[iso] = max(pop.get(iso, 0), int(props["POP_EST"]))
    # Natural Earth has no separate polygon for these, so POP_EST never lands on
    # them. Values are UN / national-statistics estimates, rounded.
    pop.update({"MC": 39000, "VA": 800, "SM": 34000, "LI": 39000,
                "SG": 5920000, "NR": 12500, "TV": 11000})

    ids = {c["iso"] for c in base}
    # Border Chain treats the border graph as undirected, so it has to be
    # symmetric. mledoze lists Sri Lanka -> India (a maritime boundary) without
    # the reverse; drop it rather than invent a land border across the Palk Strait.
    drop_borders = {("LK", "IND")}
    out = []
    for c in base:
        iso = c["iso"]
        m = mledoze.get(iso, {})
        currencies = m.get("currencies") or {}
        code = next(iter(currencies), None)
        cur = currencies.get(code, {}) if code else {}
        langs = list((m.get("languages") or {}).values())
        latlng = m.get("latlng") or [0, 0]

        out.append({
            "iso": iso,
            "iso3": m.get("cca3", ""),
            "name": c["name"],
            "aliases": c.get("aliases", []),
            "capital": c["capital"],
            "capitalAliases": c.get("capitalAliases", []),
            "region": c["region"],
            "subregion": c.get("subregion", ""),
            "flag": c["flag"],
            "emoji": c["flagEmoji"],
            "tier": c["tier"],
            "area": m.get("area") or 0,
            "pop": pop.get(iso, 0),
            "lat": round(latlng[0], 3),
            "lng": round(latlng[1], 3),
            "borders": sorted(b for b in (a3_to_a2.get(x) for x in m.get("borders") or []
                                          if (iso, x) not in drop_borders)
                              if b in ids),
            "landlocked": bool(m.get("landlocked")),
            "currency": {"code": code, "name": cur.get("name", ""), "symbol": cur.get("symbol", "")}
                        if code else None,
            "languages": langs,
            "demonym": ((m.get("demonyms") or {}).get("eng") or {}).get("m", ""),
            "phone": (m.get("callingCodes") or [""])[0],
            "tld": (m.get("tld") or [""])[0],
        })

    out.sort(key=lambda c: c["name"])

    lines = [
        "/* ===========================================================================",
        "   GeoGames - Country dataset (generated by tools/build-countries.py)",
        "   194 UN member states. Sources and licences: see ../NOTICE.md.",
        "   Do not hand-edit; re-run the build script instead.",
        "   tier: 1 = household name  2 = well known  3 = deep cut",
        "   =========================================================================== */",
        "export const COUNTRIES = [",
    ]
    for c in out:
        lines.append("  " + json.dumps(c, ensure_ascii=False, separators=(",", ":")) + ",")
    lines.append("];")
    lines.append("")
    lines.append("export const BY_ISO = Object.fromEntries(COUNTRIES.map(c => [c.iso, c]));")
    lines.append("")

    open(out_path, "w", encoding="utf-8").write("\n".join(lines))

    no_pop = [c["iso"] for c in out if not c["pop"]]
    no_border_info = sum(1 for c in out if not c["borders"] and not c["landlocked"])
    print(f"{len(out)} countries -> {out_path}")
    if no_pop:
        print("  no population:", no_pop)
    print(f"  island/coastal with no land borders: {no_border_info}")


if __name__ == "__main__":
    main()
